use crate::MsgError;

/// Client opcodes for the game client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum ClientOpcode {
    Login = 0x2EE2,
    CreateCharacter,
    DeleteCharacter,
    CharacterList,
    EnterWorld,
    LoginConfirm,
    Teleport = 0x3000,
    TeleportSavePoint,
    MultiTeleportNPC,
    SkillTeleport,
    GliderTeleport,
    GuildHouseTeleport,
    PartyDungeonTeleport,
    MoveStart = 0x30D5,
    MoveStop,
    Skill = 0x3100,
    SkillAdd,
    SkillStart,
    SkillDamage,
    SkillCastStart,
    SkillCastCancel,
    SkillChannelComplete,
    SkillChannelCancel,
    SkillMoveStart,
    SkillMoveNotify,
    SkillMoveCancel,
    SkillMoveEnd,
    SkillDamageTick,
    SkillStartItem,
    NormalAttack = 0x3110,
    DamageNormalAttack,
    ArcherAttack,
    AutoAttack,
    AutoAttackNotify,
    ItemDetailInfo = 0x3200,
    ItemListInNPC,
    ItemWeaveUse,
    ItemTransform,
    GiveEffectToItem,
    OutfitChangeItem,
    OutfitDivideReleaseItem,
    ExtendTimeSetItem,
    RideExtendItem,
    SealItem,
    SealItemClear,
    RefineItem = 0x3300,
    RefineProbability,
    BeginRefineShop,
    ChangeRefineShopName,
    RefineShopOpen,
    RandomRefineCommission,
    ChangeRandomRefineShopName,
    RandomRefineItem,
    RandomEnforceItem,
    RandomEnforceItemConfirm,
    DirectReinforce,
    TransferReinforceItem,
    GrindingItemReset,
    InitGrindingOpt,
    BestrowAttribute,
    PartySummary = 0x3400,
    PartyInvitation,
    PartyJoin,
    PartyOut,
    PartyChangeItemRule,
    PartyChangeExpRule,
    PartyChangeMaster,
    PartyExpulsion,
    PartyNotice,
    PartyRight,
    PartyChangeGroup,
    PartyEffectList,
    PartyDiceStart,
    PartyDiceJoin,
    PartyDiceChatCmd,
    PartyMemberPCOID,
    PartyTacticsTarget,
    PartyTypeChange,
    PartyFightTrim,
    PartyFightTrimVote,
    PartyJurisdictionIndun,
    PartySubMaster,
    PartyFrameMove,
    PartyDismissSubMaster,
    PartyKickVote,
    PartyMemberKickVoteStart,
    GuildCreate = 0x3500,
    GuildDelete,
    GuildMemList,
    GuildInviteMember,
    GuildKickMember,
    GuildUnregisterMe,
    GuildNoticeUpdate,
    GuildEmblem,
    GuildEmblemUpdate,
    GuildAuthority,
    GuildDelAuthority,
    GuildModifyAuthority,
    GuildMemberModifyAuth,
    GuildMasterHandover,
    GuildStorage,
    GuildStorageItemPut,
    GuildStorageItemGet,
    GuildFundsInHandDeposit,
    GuildFundsInHandWithdraw,
    GuildStorageStatementItem,
    GuildStorageStatementZeny,
    GuildDelPossible,
    GuildSkillLearn,
    GuildSkillList,
    GuildSkillLearnBook,
    GuildEmergencyCallAnswer,
    GuildTaxInquiry,
    GuildTaxWithdraw,
    GuildSelectRobe,
    GuildListRegisteredRobe,
    GuildSetBribePercent,
    Ping = 0x3600,
    CutSceneStart,
    CutSceneEnd,
    HelperDeclare,
    AppearanceChange,
    CheatTool,
    ReviewPC,
    AllowAnyoneReviewMe,
    DungeonEntranceInfo,
    DungeonLevelSelect,
    QuestionDungeonParticipateJoin,
    JobMasteryStart = 0x3610,
    JobMasteryTrain,
    JobMasteryUpgrade,
    JumpLevelUp,
    MonsterCollection = 0x3620,
    MonsterCollectionSelect,
    MonsterCollectionCombineProtein,
    MonsterCollectionUseProtein,
    PetCollection,
    PetCollectionSelect,
    PetCollectionCombineEggBlank,
    PetCollectionUsePetEgg,
    PetCollectionIncubator,
    PetCollectionEggIntoIncubator,
    PetCollectionCollectEgg,
    PetCollectionActivePet,
    PetCollectionSetActivePet,
    SiegeArmsUseStart = 0x3630,
    SiegeArmsUseEnd,
    SiegeArmsRotateStart,
    SiegeArmsRotateStop,
    SiegeArmsUseSkill,
    TrainingRoomJoin = 0x3640,
    TrainingRoomIn,
    TrainingRoomOut,
    TrainingRoomInCancel,
    Rank = 0x3650,
    RankList,
    RankerList,
    RankerBuff,
    AttendanceReward = 0x3660,
    AttendanceRewardGetItem,
    PlayTimeReward,
    PlayTimeRewardGetItem,
    ShowAttendanceState,
    MakeOfferings,
    ImprintGuardianSeal,
    ConfirmImprintGuardianSealResult,
    RegRevivalMercenary = 0x3670,
    IllusionPyramidGetMyState = 0x3680,
    IllusionPyramidDrawStage,
    IllusionPyramidGetResult,
    IllusionPyramidFinish,
    IllusionPyramidItemInfo,
    GetChanceRandomboxPrizeInfo = 0x3690,
    GetSuperChanceRandomboxState,
    GetFeverTimeRandomboxState,
    QuickSlotAdd = 0x36A0,
    QuickSlotDelete,
    QuickSlotSwap,
    RideQuickSlot,
}
impl TryFrom<u16> for ClientOpcode {
    type Error = MsgError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x2EE2 => Ok(ClientOpcode::Login),
            0x2EE3 => Ok(ClientOpcode::CreateCharacter),
            0x2EE4 => Ok(ClientOpcode::DeleteCharacter),
            0x2EE5 => Ok(ClientOpcode::CharacterList),
            0x2EE6 => Ok(ClientOpcode::EnterWorld),
            0x2EE7 => Ok(ClientOpcode::LoginConfirm),
            0x3000 => Ok(ClientOpcode::Teleport),
            0x3001 => Ok(ClientOpcode::TeleportSavePoint),
            0x3002 => Ok(ClientOpcode::MultiTeleportNPC),
            0x3003 => Ok(ClientOpcode::SkillTeleport),
            0x3004 => Ok(ClientOpcode::GliderTeleport),
            0x3005 => Ok(ClientOpcode::GuildHouseTeleport),
            0x3006 => Ok(ClientOpcode::PartyDungeonTeleport),
            0x30D5 => Ok(ClientOpcode::MoveStart),
            0x30D6 => Ok(ClientOpcode::MoveStop),
            0x3100 => Ok(ClientOpcode::Skill),
            0x3101 => Ok(ClientOpcode::SkillAdd),
            0x3102 => Ok(ClientOpcode::SkillStart),
            0x3103 => Ok(ClientOpcode::SkillDamage),
            0x3104 => Ok(ClientOpcode::SkillCastStart),
            0x3105 => Ok(ClientOpcode::SkillCastCancel),
            0x3106 => Ok(ClientOpcode::SkillChannelComplete),
            0x3107 => Ok(ClientOpcode::SkillChannelCancel),
            0x3108 => Ok(ClientOpcode::SkillMoveStart),
            0x3109 => Ok(ClientOpcode::SkillMoveNotify),
            0x310A => Ok(ClientOpcode::SkillMoveCancel),
            0x310B => Ok(ClientOpcode::SkillMoveEnd),
            0x310C => Ok(ClientOpcode::SkillDamageTick),
            0x310D => Ok(ClientOpcode::SkillStartItem),
            0x3110 => Ok(ClientOpcode::NormalAttack),
            0x3111 => Ok(ClientOpcode::DamageNormalAttack),
            0x3112 => Ok(ClientOpcode::ArcherAttack),
            0x3113 => Ok(ClientOpcode::AutoAttack),
            0x3114 => Ok(ClientOpcode::AutoAttackNotify),
            0x3200 => Ok(ClientOpcode::ItemDetailInfo),
            0x3201 => Ok(ClientOpcode::ItemListInNPC),
            0x3202 => Ok(ClientOpcode::ItemWeaveUse),
            0x3203 => Ok(ClientOpcode::ItemTransform),
            0x3204 => Ok(ClientOpcode::GiveEffectToItem),
            0x3205 => Ok(ClientOpcode::OutfitChangeItem),
            0x3206 => Ok(ClientOpcode::OutfitDivideReleaseItem),
            0x3207 => Ok(ClientOpcode::ExtendTimeSetItem),
            0x3208 => Ok(ClientOpcode::RideExtendItem),
            0x3300 => Ok(ClientOpcode::RefineItem),
            0x3301 => Ok(ClientOpcode::RefineProbability),
            0x3302 => Ok(ClientOpcode::BeginRefineShop),
            0x3303 => Ok(ClientOpcode::ChangeRefineShopName),
            0x3304 => Ok(ClientOpcode::RefineShopOpen),
            0x3305 => Ok(ClientOpcode::RandomRefineCommission),
            0x3306 => Ok(ClientOpcode::ChangeRandomRefineShopName),
            0x3307 => Ok(ClientOpcode::RandomRefineItem),
            0x3308 => Ok(ClientOpcode::RandomEnforceItem),
            0x3309 => Ok(ClientOpcode::RandomEnforceItemConfirm),
            0x330A => Ok(ClientOpcode::DirectReinforce),
            0x330B => Ok(ClientOpcode::TransferReinforceItem),
            0x330C => Ok(ClientOpcode::GrindingItemReset),
            0x330D => Ok(ClientOpcode::InitGrindingOpt),
            0x330E => Ok(ClientOpcode::BestrowAttribute),
            0x3400 => Ok(ClientOpcode::PartySummary),
            0x3401 => Ok(ClientOpcode::PartyInvitation),
            0x3402 => Ok(ClientOpcode::PartyJoin),
            0x3403 => Ok(ClientOpcode::PartyOut),
            0x3404 => Ok(ClientOpcode::PartyChangeItemRule),
            0x3405 => Ok(ClientOpcode::PartyChangeExpRule),
            0x3406 => Ok(ClientOpcode::PartyChangeMaster),
            0x3407 => Ok(ClientOpcode::PartyExpulsion),
            0x3408 => Ok(ClientOpcode::PartyNotice),
            0x3409 => Ok(ClientOpcode::PartyRight),
            0x340A => Ok(ClientOpcode::PartyChangeGroup),
            0x340B => Ok(ClientOpcode::PartyEffectList),
            0x340C => Ok(ClientOpcode::PartyDiceStart),
            0x340D => Ok(ClientOpcode::PartyDiceJoin),
            0x340E => Ok(ClientOpcode::PartyDiceChatCmd),
            0x340F => Ok(ClientOpcode::PartyMemberPCOID),
            0x3410 => Ok(ClientOpcode::PartyTacticsTarget),
            0x3411 => Ok(ClientOpcode::PartyTypeChange),
            0x3412 => Ok(ClientOpcode::PartyFightTrim),
            0x3413 => Ok(ClientOpcode::PartyFightTrimVote),
            0x3414 => Ok(ClientOpcode::PartyJurisdictionIndun),
            0x3415 => Ok(ClientOpcode::PartySubMaster),
            0x3416 => Ok(ClientOpcode::PartyFrameMove),
            0x3417 => Ok(ClientOpcode::PartyDismissSubMaster),
            0x3418 => Ok(ClientOpcode::PartyKickVote),
            0x3419 => Ok(ClientOpcode::PartyMemberKickVoteStart),
            0x3500 => Ok(ClientOpcode::GuildCreate),
            0x3501 => Ok(ClientOpcode::GuildDelete),
            0x3502 => Ok(ClientOpcode::GuildMemList),
            0x3503 => Ok(ClientOpcode::GuildInviteMember),
            0x3504 => Ok(ClientOpcode::GuildKickMember),
            0x3505 => Ok(ClientOpcode::GuildUnregisterMe),
            0x3506 => Ok(ClientOpcode::GuildNoticeUpdate),
            0x3507 => Ok(ClientOpcode::GuildEmblem),
            0x3508 => Ok(ClientOpcode::GuildEmblemUpdate),
            0x3509 => Ok(ClientOpcode::GuildAuthority),
            0x350A => Ok(ClientOpcode::GuildDelAuthority),
            0x350B => Ok(ClientOpcode::GuildModifyAuthority),
            0x350C => Ok(ClientOpcode::GuildMemberModifyAuth),
            0x350D => Ok(ClientOpcode::GuildMasterHandover),
            0x350E => Ok(ClientOpcode::GuildStorage),
            0x350F => Ok(ClientOpcode::GuildStorageItemPut),
            0x3510 => Ok(ClientOpcode::GuildStorageItemGet),
            0x3511 => Ok(ClientOpcode::GuildFundsInHandDeposit),
            0x3512 => Ok(ClientOpcode::GuildFundsInHandWithdraw),
            0x3513 => Ok(ClientOpcode::GuildStorageStatementItem),
            0x3514 => Ok(ClientOpcode::GuildStorageStatementZeny),
            0x3515 => Ok(ClientOpcode::GuildDelPossible),
            0x3516 => Ok(ClientOpcode::GuildSkillLearn),
            0x3517 => Ok(ClientOpcode::GuildSkillList),
            0x3518 => Ok(ClientOpcode::GuildSkillLearnBook),
            0x3519 => Ok(ClientOpcode::GuildEmergencyCallAnswer),
            0x351A => Ok(ClientOpcode::GuildTaxInquiry),
            0x351B => Ok(ClientOpcode::GuildTaxWithdraw),
            0x351C => Ok(ClientOpcode::GuildSelectRobe),
            0x351D => Ok(ClientOpcode::GuildListRegisteredRobe),
            0x351E => Ok(ClientOpcode::GuildSetBribePercent),
            0x3600 => Ok(ClientOpcode::Ping),
            0x3601 => Ok(ClientOpcode::CutSceneStart),
            0x3602 => Ok(ClientOpcode::CutSceneEnd),
            0x3603 => Ok(ClientOpcode::HelperDeclare),
            0x3604 => Ok(ClientOpcode::AppearanceChange),
            0x3605 => Ok(ClientOpcode::CheatTool),
            0x3606 => Ok(ClientOpcode::ReviewPC),
            0x3607 => Ok(ClientOpcode::AllowAnyoneReviewMe),
            0x3608 => Ok(ClientOpcode::DungeonEntranceInfo),
            0x3609 => Ok(ClientOpcode::DungeonLevelSelect),
            0x360A => Ok(ClientOpcode::QuestionDungeonParticipateJoin),
            0x3610 => Ok(ClientOpcode::JobMasteryStart),
            0x3611 => Ok(ClientOpcode::JobMasteryTrain),
            0x3612 => Ok(ClientOpcode::JobMasteryUpgrade),
            0x3613 => Ok(ClientOpcode::JumpLevelUp),
            0x3620 => Ok(ClientOpcode::MonsterCollection),
            0x3621 => Ok(ClientOpcode::MonsterCollectionSelect),
            0x3622 => Ok(ClientOpcode::MonsterCollectionCombineProtein),
            0x3623 => Ok(ClientOpcode::MonsterCollectionUseProtein),
            0x3624 => Ok(ClientOpcode::PetCollection),
            0x3625 => Ok(ClientOpcode::PetCollectionSelect),
            0x3626 => Ok(ClientOpcode::PetCollectionCombineEggBlank),
            0x3627 => Ok(ClientOpcode::PetCollectionUsePetEgg),
            0x3628 => Ok(ClientOpcode::PetCollectionIncubator),
            0x3629 => Ok(ClientOpcode::PetCollectionEggIntoIncubator),
            0x362A => Ok(ClientOpcode::PetCollectionCollectEgg),
            0x362B => Ok(ClientOpcode::PetCollectionActivePet),
            0x362C => Ok(ClientOpcode::PetCollectionSetActivePet),
            0x3630 => Ok(ClientOpcode::SiegeArmsUseStart),
            0x3631 => Ok(ClientOpcode::SiegeArmsUseEnd),
            0x3632 => Ok(ClientOpcode::SiegeArmsRotateStart),
            0x3633 => Ok(ClientOpcode::SiegeArmsRotateStop),
            0x3634 => Ok(ClientOpcode::SiegeArmsUseSkill),
            0x3640 => Ok(ClientOpcode::TrainingRoomJoin),
            0x3641 => Ok(ClientOpcode::TrainingRoomIn),
            0x3642 => Ok(ClientOpcode::TrainingRoomOut),
            0x3643 => Ok(ClientOpcode::TrainingRoomInCancel),
            0x3650 => Ok(ClientOpcode::Rank),
            0x3651 => Ok(ClientOpcode::RankList),
            0x3652 => Ok(ClientOpcode::RankerList),
            0x3653 => Ok(ClientOpcode::RankerBuff),
            0x3660 => Ok(ClientOpcode::AttendanceReward),
            0x3661 => Ok(ClientOpcode::AttendanceRewardGetItem),
            0x3662 => Ok(ClientOpcode::PlayTimeReward),
            0x3663 => Ok(ClientOpcode::PlayTimeRewardGetItem),
            0x3664 => Ok(ClientOpcode::ShowAttendanceState),
            0x3665 => Ok(ClientOpcode::MakeOfferings),
            0x3666 => Ok(ClientOpcode::ImprintGuardianSeal),
            0x3667 => Ok(ClientOpcode::ConfirmImprintGuardianSealResult),
            0x3670 => Ok(ClientOpcode::RegRevivalMercenary),
            0x3680 => Ok(ClientOpcode::IllusionPyramidGetMyState),
            0x3681 => Ok(ClientOpcode::IllusionPyramidDrawStage),
            0x3682 => Ok(ClientOpcode::IllusionPyramidGetResult),
            0x3683 => Ok(ClientOpcode::IllusionPyramidFinish),
            0x3684 => Ok(ClientOpcode::IllusionPyramidItemInfo),
            0x3690 => Ok(ClientOpcode::GetChanceRandomboxPrizeInfo),
            0x3691 => Ok(ClientOpcode::GetSuperChanceRandomboxState),
            0x3692 => Ok(ClientOpcode::GetFeverTimeRandomboxState),
            0x36A0 => Ok(ClientOpcode::QuickSlotAdd),
            0x36A1 => Ok(ClientOpcode::QuickSlotDelete),
            0x36A2 => Ok(ClientOpcode::QuickSlotSwap),
            0x36A3 => Ok(ClientOpcode::RideQuickSlot),
            _ => Err(MsgError::UnknownOpcode(value)),
        }
    }
}
