use crate::MsgError;

/// Server-to-client opcodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum ServerOpcode {
    Login = 0x2EE7,
    CreateCharacter,
    DeleteCharacter,
    CharacterList,
    EnterWorld,
    Time = 0x2EF0,
    TimeToLoginPC,
    Teleport = 0x3005,
    TeleportSavePoint,
    MultiTeleportNPC,
    SkillTeleport,
    GliderTeleport,
    GuildHouseTeleport,
    PartyDungeonTeleport,
    UpdatePCPos,
    PCMoveStateChange = 0x3010,
    MoveStart = 0x30DA,
    MoveStop,
    Skill = 0x3105,
    SkillAdd,
    SkillStart,
    UseSkillStart,
    SkillDamage,
    SkillError,
    SkillCastStart,
    SkillCastCancel,
    SkillChannelComplete,
    SkillChannelCancel,
    SkillMoveStart,
    SkillMoveNotify,
    SkillMoveCancel,
    SkillMoveEnd,
    SkillDamageTick,
    SkillStartItem,
    NormalAttack,
    ErrorNormalAttack,
    DamageNormalAttack,
    ArcherAttack,
    AutoAttack,
    AutoAttackNotify,
    UseSkillStart = 0x3120,
    SkillDamage,
    SkillDamageTick,
    SkillCastStart,
    SkillCastCancel,
    SkillMoveStart,
    SkillMoveNotify,
    SkillMoveCancel,
    SkillMoveEnd,
    SkillCoolTime,
    CoolTimeClear,
    CoolTimeLockRelease,
    SkillStartError,
    SkillDamageError,
    AttackDamage,
    NormalAttackStart,
    RevivalSkill,
    ItemDetailInfo = 0x3205,
    ItemListInNPC,
    ItemWeaveUse,
    ItemTransform,
    GiveEffectToItem,
    OutfitChangeItem,
    OutfitDivideReleaseItem,
    ExtendTimeSetItem,
    RideExtendItem,
    SealItem,
    SealItemClear,
    UseCashItem,
    OpenItemSocket,
    AttachSocket,
    ExtractSocket,
    UseDyeItem,
    GiveItemRemainTime,
    ItemUpdate = 0x3220,
    TimedItemInfo,
    ExpiredItemInfo,
    TimeSetItemStart,
    TimeSetItemEnd,
    PCItemTrait,
    RefineItem = 0x3305,
    RefineProbability,
    BeginRefineShop,
    ChangeRefineShopName,
    RefineShopOpen,
    RandomRefineCommission,
    ChangeRandomRefineShopName,
    RandomRefineItem,
    RandomEnforceItem,
    RandomEnforceItemConfirm,
    DirectReinforce,
    TransferReinforceItem,
    GrindingItemReset,
    InitGrindingOpt,
    BestrowAttribute,
    RandomItemInBoxList,
    RandomItemSelected,
    BeginRefineShop = 0x3320,
    ChangeRefineShopName,
    RefineCommissionToBuyer,
    RefineItemNotice,
    ChangeRandomRefineShopName,
    RandomRefineCommissionToBuyer,
    PartySummary = 0x3405,
    PartyInvitation,
    PartyJoin,
    PartyOut,
    PartyChangeItemRule,
    PartyChangeExpRule,
    PartyChangeMaster,
    PartyExpulsion,
    PartyNotice,
    PartyRight,
    PartyChangeGroup,
    PartyEffectList,
    PartyDiceStart,
    PartyDiceJoin,
    PartyDiceChattingCmd,
    PartyMemberPcOid,
    PartyTacticsTarget,
    PartyTacticsTargetError,
    PartyTypeChange,
    PartyFightingTrim,
    PartyFightingTrimVote,
    PartyJurisdictionIndun,
    PartySubMaster,
    PartyFrameMove,
    PartyDismissSubMaster,
    PartyKickVote,
    PartyMemberKickVoteStart,
    PartyMatchDetail = 0x3425,
    PartyMatchWhisper,
    PartyMatchApplyMsg,
    PartyMatchSearchApply,
    PartyMatchFindDungeon,
    PartyMatchFindDungeonRandom,
    PartyMatchInProgressInfo,
    PartyMatchFindDungeonCancel,
    PartyMatchFindDungeonJoinSelect,
    PartyMatchSearchInvite,
    PartyMatchIntoDungeonParticipate,
    PartyMatchOutDungeon,
    PartyMatchRejoinDungeon,
    FindPartySelectRole,
    FindPartySelectRoleCancel,
    PartyTypeChange = 0x3440,
    PartySubMaster,
    PartyFrameMove,
    PartyDismissSubmaster,
    PartyFightTrimStart,
    PartyFightTrimResult,
    PartyDiceChatCmd,
    PartyItemListClose,
    PartyMemberKickVote,
    ResultPartyKickVote,
    EntryPartyError,
    PartyMatchFindDungeonStartJoinMessage,
    PartyMatchFindDungeonJoinFail,
    ResultFindPartySelectRole,
    FindPartyDungeonSelectRolePlease,
    DungeonFindPartyCancel,
    DungeonFindInProgressJoinMsg,
    DungeonFindPcPrivateIndunJoin,
    GuildCreate = 0x3505,
    GuildDelete,
    GuildMemList,
    GuildInviteMember,
    GuildKickMember,
    GuildUnregisterMe,
    GuildNoticeUpdate,
    GuildEmblem,
    GuildEmblemUpdate,
    GuildAuthority,
    GuildDeleteAuthority,
    GuildModifyAuthority,
    GuildMemberModifyAuth,
    GuildMasterHandover,
    GuildStorage,
    OpenGuildStorage,
    GuildStorageItemPut,
    GuildStorageItemGet,
    GuildFundsInHandDeposit,
    GuildFundsInHandWithdraw,
    GuildStorageStatementItem,
    GuildStorageStatementZeny,
    GuildDelPossible,
    GuildSkillLearn,
    GuildSkillList,
    GuildGmInitSkillList,
    GuildSkillLearnBook,
    GuildEmergencyCallAsk,
    GuildTaxInquiry,
    GuildTaxWithdraw,
    GuildSelectRobe,
    GuildListRegisteredRobe,
    GuildSetBribePercent,
    CanRenameGuild,
    RenameGuild,
    GuildHouseLottery = 0x3530,
    GuildHouseTicket,
    GuildHouseResult,
    GuildHouseLotteryRank,
    GuildMemberAdd = 0x3540,
    GuildMemberRemove,
    GuildKickMember,
    GuildInviteMember,
    GuildInviteYou,
    GuildNoticeUpdated,
    UpdateGuildEmblem,
    GuildDeleteAuthority,
    GuildModifyAuthority,
    GuildMemberModifyAuthority,
    GuildMasterHandover,
    AddGuildStorageItem,
    DeleteGuildStorageItem,
    UpdateGuildFundsInHand,
    GuildSkillLearn,
    GuildBribeHunting,
    GuildBribePcLevelUp,
    GuildLevelUp,
    GuildHandoverMemberBribePointToGuildMaster,
    GuildRobeChanged,
    GuildHouseAnnounce,
    Ping = 0x3605,
    CutSceneStart,
    CutSceneEnd,
    HelperDeclare,
    AppearanceChange,
    CheatTool,
    ReviewPC,
    AllowAnyoneReviewMe,
    DungeonEntranceInfo,
    DungeonLevelSelect,
    DungeonReset,
    QuestionDungeonParticipationJoin,
    JobMasteryStart = 0x3615,
    JobMasteryTrain,
    JobMasteryUpgrade,
    JumpLevelUp,
    MonsterCollection = 0x3625,
    MonsterCollectionSelect,
    MonsterCollectionCombineProtein,
    MonsterCollectionUseProtein,
    MonsterCollectionSelectSkill,
    PetCollection,
    PetCollectionSelected,
    PetCollectionCombineEggBlank,
    PetCollectionUsePetEgg,
    PetCollectionIncubator,
    PetCollectionEggIntoIncubator,
    PetCollectionCollectEgg,
    PetCollectionActivePet,
    PetCollectionSetActivePet,
    PetCollectionSelectSkill,
    MonsterCollectionNotify = 0x3640,
    MonsterCollectionSkill,
    MonsterCollectionSelectSkillNotify,
    PetCollectionNotify,
    PetCollectionSkill,
    PetCollectionSelectSkillNotify,
    SiegeArmsUseStart = 0x3650,
    SiegeArmsUseEnd,
    SiegeArmsRotationStart,
    SiegeArmsRotationStop,
    SiegeArmsUseSkill,
    CertifyFieldPVP,
    ReqErrorFieldPVP,
    SiegeStart = 0x3660,
    SiegeStartBeforehandStart,
    SiegeStartBeforehandRestart,
    SiegeOccupy,
    SiegeStatusInfo,
    SiegeHpStatus,
    SiegeArmsSettingChanged,
    SiegeArmsUserChanged,
    SiegeArmsRotateStartNotify,
    SiegeArmsRotateStopNotify,
    StartFieldPVP,
    GetInFieldPVP,
    GetOutFieldPVP,
    CancelFieldPVP,
    AcceptFieldPVP,
    ResultFieldPVP,
    PVPPCInfo,
    TrainingRoomJoin = 0x3680,
    TrainingRoomIn,
    TrainingRoomOut,
    TrainingRoomInCancel,
    ColosseumInCancel,
    TrainingRoomJoinMsg = 0x3690,
    TrainingRoomState,
    TrainingRoomPartyState,
    TrainingRoomBattleState,
    TrainingRoomBattleStateAll,
    TrainingRoomPcKill,
    TrainingRoomNpcKill,
    TrainingRoomEnd,
    TrainingRoomEffectList,
    TrainingRoomPcKillByNpc,
    TrainingRoomNpcKillByNpc,
    TrainingRoomRematchingParty,
    ColosseumStart = 0x36A0,
    ColosseumBeforehandStart,
    ColosseumWin,
    ColosseumJoinCount,
    ColosseumRoundStateChange,
    ColosseumRoundClear,
    ColosseumLimitJoin,
    ColosseumRoundStartPlayerList,
    ColosseumRankUpdate,
    ColosseumPCKillCount,
    ColosseumScoreBoard,
    ColosseumJoinMsg,
    ColosseumPartyState,
    ColosseumRematchingParty,
    Rank = 0x36B0,
    RankList,
    RankerList,
    RankerBuff,
    RankerChange = 0x36B8,
    RankTopList,
    AttendanceReward = 0x36C0,
    AttendanceRewardGetItem,
    PlayTimeReward,
    PlayTimeRewardGetItem,
    ShowAttendanceState,
    MakeOfferings,
    ImprintGuardianSeal,
    ConfirmImprintGuardianSealResult,
    ShowAttendanceStateNfy = 0x36D0,
    EventClear,
    EventEnter,
    EventSpawnNDropNotice,
    WorldEventTrigger,
    WebEventWinnerNotice,
    CountLimitItemNotice,
    RegRevivalMercenary = 0x36E0,
    RevivalMercenaryState = 0x36E8,
    IllusionPyramidGetMyState = 0x36F0,
    IllusionPyramidDrawStage,
    IllusionPyramidGetResult,
    IllusionPyramidFinish,
    IllusionPyramidItemInfo,
    BeginLevelOnStage = 0x3700,
    FailureLevelOnStage,
    ReadyOkNextLevelOnStage,
    EndOfStageDungeon,
    DungeonLevelSelectInfo,
    DungeonBindResetWarning,
    DungeonBindReset,
    DungeonBindMissionInfo,
    JoinDungeonIsRandom,
    RandomDungeonCompleteGift,
    GetChanceRandomboxPrizeInfo = 0x3710,
    GetSuperChanceRandomboxState,
    GetFeverTimeRandomboxState,
    QuickSlotAdd = 0x3720,
    QuickSlotDelete,
    QuickSlotSwap,
    RideQuickSlot,
    ChangeProJobDeleteQuickSlot = 0x3728,
    CutSceneStart = 0x3730,
    HelperNotice,
    CurrencyChange,
    YouAreStressed,
    PushingStart,
    JobMasteryPointChange,
    ChangeProJob,
    ChangeProJobQuest,
    ChangeProJobGuardianSkill,
    PCEquipView,
    CharTransform,
    TargetInfo,
    AggroChange,
    NPCEffect,
    NPCChat,
    NPCBattleLevelUp,
    FallDamage,
    SwimGuage,
    AccountGiftCount,
    AccountGiftInfo,
    AccountGiftReceive,
    FuncObjectControlStatus,
    UpdateQuestComplete,
    UpdateKharaComplete,
    DeleteAcceptedKhara,
    KharaTitleChange,
    OpenRemoteBank,
    OpenRemoteShop,
    MarketRiseUpEnd,
    AuctionSystemMessage,
    PlayScene,
    ExcuteBuffHandle,
    CardBookAlramEndTime,
    CardBookChargeTime,
    CardBookChargeTimeEnd,
    CardEquipTakeOff,
    CardDurabilityUpdate,
    HShieldErrorDetect,
    TPlusInfo,
    PCCafeRevivalInfo,
    SpinelRevivalInfo,
    GRAInternetCafeGradeChange,
}

impl TryFrom<u16> for ServerOpcode {
    type Error = MsgError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x2EE7 => Ok(ServerOpcode::Login),
            0x2EF0 => Ok(ServerOpcode::Time),
            0x3005 => Ok(ServerOpcode::Teleport),
            0x3010 => Ok(ServerOpcode::PCMoveStateChange),
            0x30DA => Ok(ServerOpcode::MoveStart),
            0x3105 => Ok(ServerOpcode::Skill),
            0x3120 => Ok(ServerOpcode::UseSkillStart),
            0x3205 => Ok(ServerOpcode::ItemDetailInfo),
            0x3220 => Ok(ServerOpcode::ItemUpdate),
            0x3305 => Ok(ServerOpcode::RefineItem),
            0x3320 => Ok(ServerOpcode::BeginRefineShop),
            0x3405 => Ok(ServerOpcode::PartySummary),
            0x3425 => Ok(ServerOpcode::PartyMatchDetail),
            0x3440 => Ok(ServerOpcode::PartyTypeChange),
            0x3505 => Ok(ServerOpcode::GuildCreate),
            0x3530 => Ok(ServerOpcode::GuildHouseLottery),
            0x3540 => Ok(ServerOpcode::GuildMemberAdd),
            0x3605 => Ok(ServerOpcode::Ping),
            0x3615 => Ok(ServerOpcode::JobMasteryStart),
            0x3625 => Ok(ServerOpcode::MonsterCollection),
            0x3640 => Ok(ServerOpcode::MonsterCollectionNotify),
            0x3650 => Ok(ServerOpcode::SiegeArmsUseStart),
            0x3660 => Ok(ServerOpcode::SiegeStart),
            0x3680 => Ok(ServerOpcode::TrainingRoomJoin),
            0x3690 => Ok(ServerOpcode::TrainingRoomJoinMsg),
            0x36A0 => Ok(ServerOpcode::ColosseumStart),
            0x36B0 => Ok(ServerOpcode::Rank),
            0x36B8 => Ok(ServerOpcode::RankTopList),
            0x36C0 => Ok(ServerOpcode::AttendanceReward),
            0x36D0 => Ok(ServerOpcode::ShowAttendanceStateNfy),
            0x36E0 => Ok(ServerOpcode::RegRevivalMercenary),
            0x36E8 => Ok(ServerOpcode::RevivalMercenaryState),
            0x36F0 => Ok(ServerOpcode::IllusionPyramidGetMyState),
            0x3700 => Ok(ServerOpcode::BeginLevelOnStage),
            0x3710 => Ok(ServerOpcode::GetChanceRandomboxPrizeInfo),
            0x3720 => Ok(ServerOpcode::QuickSlotAdd),
            0x3728 => Ok(ServerOpcode::ChangeProJobDeleteQuickSlot),
            0x3730 => Ok(ServerOpcode::CutSceneStart),
            0x3731 => Ok(ServerOpcode::HelperNotice),
            0x3732 => Ok(ServerOpcode::CurrencyChange),
            0x3733 => Ok(ServerOpcode::YouAreStressed),
            0x3734 => Ok(ServerOpcode::PushingStart),
            0x3735 => Ok(ServerOpcode::JobMasteryPointChange),
            0x3736 => Ok(ServerOpcode::ChangeProJob),
            0x3737 => Ok(ServerOpcode::ChangeProJobQuest),
            0x3738 => Ok(ServerOpcode::ChangeProJobGuardianSkill),
            0x3739 => Ok(ServerOpcode::PCEquipView),
            0x373A => Ok(ServerOpcode::CharTransform),
            0x373B => Ok(ServerOpcode::TargetInfo),
            0x373C => Ok(ServerOpcode::AggroChange),
            0x373D => Ok(ServerOpcode::NPCEffect),
            0x373E => Ok(ServerOpcode::NPCChat),
            0x373F => Ok(ServerOpcode::NPCBattleLevelUp),
            0x3740 => Ok(ServerOpcode::FallDamage),
            0x3741 => Ok(ServerOpcode::SwimGauge),
            0x3742 => Ok(ServerOpcode::AccountGiftCount),
            0x3743 => Ok(ServerOpcode::AccountGiftInfo),
            0x3744 => Ok(ServerOpcode::AccountGiftReceive),
            0x3745 => Ok(ServerOpcode::FuncObjectControlStatus),
            0x3746 => Ok(ServerOpcode::UpdateQuestComplete),
            0x3747 => Ok(ServerOpcode::UpdateKharaComplete),
            0x3748 => Ok(ServerOpcode::DeleteAcceptedKhara),
            0x3749 => Ok(ServerOpcode::KharaTitleChange),
            0x374A => Ok(ServerOpcode::OpenRemoteBank),
            0x374B => Ok(ServerOpcode::OpenRemoteShop),
            0x374C => Ok(ServerOpcode::MarketRiseUpEnd),
            0x374D => Ok(ServerOpcode::AuctionSystemMessage),
            0x374E => Ok(ServerOpcode::PlayScene),
            0x374F => Ok(ServerOpcode::ExecuteBuffHandle),
            0x3750 => Ok(ServerOpcode::CardBookAlarmEndTime),
            0x3751 => Ok(ServerOpcode::CardBookChargeTime),
            0x3752 => Ok(ServerOpcode::CardBookChargeTimeEnd),
            0x3753 => Ok(ServerOpcode::CardEquipTakeOff),
            0x3754 => Ok(ServerOpcode::CardDurabilityUpdate),
            0x3755 => Ok(ServerOpcode::HShieldErrorDetect),
            0x3756 => Ok(ServerOpcode::TPlusInfo),
            0x3757 => Ok(ServerOpcode::PCCafeRevivalInfo),
            0x3758 => Ok(ServerOpcode::SpinelRevivalInfo),
            0x3759 => Ok(ServerOpcode::GRAInternetCafeGradeChange),
            _ => return Err(MsgError::Opcode(value)),
        }
    }
}
